### PR TITLE
Fleshed out the autoMatchFields feature

### PR DESCRIPTION
**Pull request by spacewaffle**
This pr does four things:
- adds the ability for autoMatchFields to ignore the cases of field names and csv headers when matching.
- adds props to toggle these two features on/off called autoMatchFields and autoMatchIgnoreCase.
- adds documentation for autoMatchFields and autoMatchIgnoreCase to the readme
- autoMatchFields will ignore leading and trailing white space when doing comparisons.

### CODE REVIEW

**Comment by spacewaffle** [comment]
Latest commit was added to ensure that autoMatchFields supports matchFields if it is defined as an object instead of an array.

**Comment by jgile** [comment]
looks good - can you please add tests for auto-matching?  thanks.

**Comment by Glenn-Domin** [comment]
If we can get this merged soon that'd be great to use in a production site.

**Comment by spacewaffle** [comment]
Just added tests.

**Comment by Glenn-Domin** [comment]
Works great, thanks! This will save our client a lot of effort.

**Comment by Glenn-Domin** [comment]
Okay there's a bug. 😄 
@spacewaffle take this example. All fields match correctly BUT nothing gets added to the `v-model` variable `csvData`. The callback also doesn't fire.
What DOES work is if I leave one field unmatched. As soon as I manually match it then `csvData` will be populated and the callback will fire.
```
<vue-csv-import
  v-model="csvData"
  :headers="true"
  :callback="checkCSV"
  :autoMatchFields="true"
  :autoMatchIgnoreCase="true"
  class="position-relative"
  :map-fields="{
    client: 'Client',
    external_ref: 'Order ID/#',
    name: 'Customer Name',
    shipping_address_1: 'Shipping Address 1',
    shipping_address_2: 'Shipping Address 2',
    city: 'City',
    state: 'State',
    postcode: 'Postcode',
    country: 'Country',
    shipping_method: 'Shipping Method',
    email: 'Email for Tracking',
    print_url: 'Artwork link',
    preview_url: 'Preview File link',
    brand: 'Brand',
    styleNumber: 'Style',
    size: 'Size',
    color: 'Color',
    quantity: 'Quantity',
    location: 'Print_location',
    print_x_offset: 'X_Offset',
    print_y_offset: 'Y_Offset'
  }"
>
```

**Comment by spacewaffle** [comment]
Can you provide an example csv to replicate the issue?

**Comment by Glenn-Domin** [comment]
Yes that's right. If all fields are automatically matched, nothing will be added using v-model. If at least one field is set manually though, it'll function as expected.
It seems to happen in every instance in our client's application, but here's one:
```
              <vue-csv-import
                v-model="csvData"
                :callback="sendCSV"
                :autoMatchFields="true"
                :autoMatchIgnoreCase="true"
                :headers="true"
                class="position-relative"
                :map-fields="{
                  sku: 'SKU',
                  client_sku: 'External SKU',
                  client_color: 'Color',
                  client_size: 'Size',
                  client_style: 'Style',
                  client_brand: 'Brand',
                  client_description: 'Description',
                  blank_price: 'Blank Price',
                  large_print: 'Large_Print',
                  small_print: 'Small_Print'
                }"
              >
```
And the CSV file:
```
SKU,Style,Color,Size,Brand,Description, Blank price , Large_Print , Small_Print ,External SKU
P873,5000,Black,S,Gildan,Classic,$3.54,$7.85,$5.00,
P919,5000,Navy,L,Gildan,Classic,$3.54,$7.85,$5.00,
P918,5000,Navy,XL,Gildan,Classic,$3.54,$7.85,$5.00,
P870,5000,Black,XL,Gildan,Classic,$3.54,$7.85,$5.00,
P914,5000,Heather Grey,M,Gildan,Classic,$3.54,$7.85,$5.00,
P913,5000,Heather Grey,L,Gildan,Classic,$4.68,$7.85,$5.00,
P874,5000,Black,2XL,Gildan,Classic,$2.58,$6.50,$5.00,
P819,6004,Heather Grey,M,Bella,SS,$2.58,$6.50,$5.00,
P677,3480,Black,L,Bella,Unisex,$2.58,$6.50,$5.00,
P272,6101,Black,L,LAT,SS,$2.58,$6.50,$5.00,
P505,99200,Heather Grey,L,Bella,HW,$2.58,$6.50,$5.00,
P510,99200,Navy,XL,Bella,HW,$3.48,$6.50,$5.00,
P512,99200,Navy,S,Bella,HW,$3.48,$6.50,$5.00,
P277,6101,Black,M,LAT,SS,$3.48,$6.50,$5.00,
```
P.S. Clearly the trim function is working well!

**Comment by spacewaffle** [comment]
latest fix here. @jgile please check when you can.
https://github.com/jgile/vue-csv-import/pull/37

**Pull request merged**
