### PR TITLE
add auto matching fields

### PR DESCRIPTION
**Pull request by spacewaffle**
This creates a watcher on sample that will auto match fields and add them to the map object when sample is available.

### CODE REVIEW

**Comment by scramatte** [comment]
Hello,

Can you add doc/example ?

Regards

**Comment by spacewaffle** [comment]
I've got a new pr with some documentation and options to toggle it on/off.

**Comment by Glenn-Domin** [comment]
This is great, thanks!
I'd suggest also trimming white-space before and after the field. When I tried this out I was wondering why a particular field wasn't being matched automatically. Turns out there was a space before and after the field. I had to change the file to make it work.

**Comment by spacewaffle** [comment]
@Glenn-Domin Thanks for the suggestion. I'll add that to my next pr.

**Comment by Glenn-Domin** [comment]
After testing some more I've noticed matching will happen with an array of mapped fields as expected, but we may be able to change things a bit when an object is used.
For example, in a project I have the following fields being passed to the component. The logic will attempt to match the key `client` to the CSV field instead of the string `'Client'`. IMHO I think this is backward, in that the value should be matched.
```
{
  client: 'Client',
  external_ref: 'Order ID/#',
  name: 'Customer Name',
  shipping_address_1: 'Shipping Address 1',
  shipping_address_2: 'Shipping Address 2',
  city: 'City',
  state: 'State'
}
```

**Comment by spacewaffle** [comment]
Ahh good call. I'll add that in. Please continue this conversation at the new pr.
https://github.com/jgile/vue-csv-import/pull/29

**Pull request merged**
